language: java

jdk:
  - oraclejdk8

addons:
  apt:
    packages:
      - oracle-java8-installer

sudo: false
install: mvn install -DskipTests=true -Dmaven.javadoc.skip=true -B -V -source 8
script: mvn test